// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcp8DcgPSVRr-Ylf0althKc1T4H4RDPNs',
    appId: '1:967510021533:web:4fbb9a481ff15c085ecb74',
    messagingSenderId: '967510021533',
    projectId: 'tractor-ecom-app',
    authDomain: 'tractor-ecom-app.firebaseapp.com',
    storageBucket: 'tractor-ecom-app.appspot.com',
    measurementId: 'G-9P126QT6T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh_ygGojbBC4LzBj7mgmNc26XPQQGj7cQ',
    appId: '1:967510021533:android:cfc7654ca8c506485ecb74',
    messagingSenderId: '967510021533',
    projectId: 'tractor-ecom-app',
    storageBucket: 'tractor-ecom-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTOzZmg1V_11kE6GTeQedxVlkoudoA3Ks',
    appId: '1:967510021533:ios:10e1fe59c90905e05ecb74',
    messagingSenderId: '967510021533',
    projectId: 'tractor-ecom-app',
    storageBucket: 'tractor-ecom-app.appspot.com',
    iosClientId: '967510021533-ed6idd254jsc28mrgibo2ibb4b19loe6.apps.googleusercontent.com',
    iosBundleId: 'com.jaydev.ecom.projectEcommerce',
  );
}
